import { 
  Globe, 
  Smartphone, 
  Palette, 
  Megaphone, 
  Shield, 
  Monitor, 
  ShoppingCart,
  Code,
  Layout,
  Settings,
  Zap,
  Building,
  LucideIcon,
  Briefcase,
  Users,
  FileText,
  Image,
  Video,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  CheckCircle,
  ArrowRight,
  ChevronRight,
  Star,
  Heart,
  Target,
  Rocket,
  TrendingUp,
  Database,
  Cpu,
  BarChart,
  Lightbulb,
  Award,
  Workflow,
  Search,
  PenTool,
  Home,
  Menu,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Navigation,
  Compass,
  MessageCircle,
  MessageSquare,
  Send,
  Bell,
  BellRing,
  Headphones,
  Mic,
  Folder,
  FolderOpen,
  File,
  FileCheck,
  Download,
  Upload,
  Save,
  Edit,
  Trash,
  Copy,
  Clipboard,
  DollarSign,
  CreditCard,
  Package,
  Store,
  TrendingDown,
  PieChart,
  LineChart,
  Share2,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  Share,
  Wifi,
  Bluetooth,
  Cloud,
  CloudUpload,
  CloudDownload,
  Server,
  HardDrive,
  Plus,
  Minus,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Filter,
  Grid,
  List,
  Layers,
  Link,
  ExternalLink,
  RefreshCw,
  Power,
  Camera,
  Music,
  Film,
  Gamepad2,
  Coffee,
  Gift,
  Flame,
  Droplet,
  Sun,
  Moon,
  Sparkles,
  Handshake,
  UserCheck,
  UserCog,
  ClipboardCheck,
  ClipboardList,
  CheckSquare,
  FileCheck2,
  FileQuestion,
  FileSearch,
  FileCode,
  FileImage,
  FileVideo,
  FileMusic,
  FileSpreadsheet,
  Presentation,
  BookOpen,
  GraduationCap,
  School,
  BookMarked,
  Newspaper,
  Radio,
  Podcast,
  Tv,
  MonitorSpeaker,
  Laptop,
  Tablet,
  MousePointerClick,
  Keyboard,
  Printer,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Code2,
  Brackets,
  Braces,
  Bug,
  TestTube,
  FlaskConical,
  Paintbrush,
  Paintbrush2,
  Brush,
  Eraser,
  Ruler,
  Scissors,
  Crop,
  Layers2,
  Layers3,
  Frame,
  Activity,
  Signal,
  Volume2,
  VolumeX,
  ShoppingBag,
  ShoppingBasket,
  Receipt,
  Tag,
  Tags,
  Percent,
  Ticket,
  QrCode,
  Barcode,
  ScanLine,
  LifeBuoy,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  PhoneOff,
  Plane,
  Car,
  Bike,
  Ship,
  Train,
  Bus,
  Navigation2,
  Map,
  MapPinned,
  Route,
  HeartPulse,
  Dumbbell,
  Stethoscope,
  Pill,
  Utensils,
  UtensilsCrossed,
  ChefHat,
  Wine,
  Beer,
  Building2,
  Factory,
  Warehouse,
  Hotel,
  Book,
  BookOpenCheck,
  School2,
  Wallet,
  Banknote,
  Coins,
  ReceiptText,
  Calculator,
  Scale,
  Gavel,
  FileJson,
  FileType,
  FileX,
  FilePlus,
  FileMinus,
  FileEdit,
  Users2,
  UserPlus,
  UserMinus,
  UserX,
  UserCircle,
  UserSquare,
  UserRound,
  Timer,
  TimerReset,
  TimerOff,
  CalendarDays,
  CalendarCheck,
  CalendarClock,
  CalendarX,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Sunrise,
  Sunset,
  Wind,
  Wrench,
  Hammer,
  Nut,
  Cog,
  Sliders,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  Key,
  KeyRound,
  Fingerprint,
  Scan,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Volume1,
  VideoOff,
  MicOff,
  AtSign,
  MailOpen,
  MailCheck,
  MailX,
  MessageSquareReply,
  MessageSquareText,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderCheck,
  FolderSearch,
  FolderKanban,
  FolderTree,
  BarChart2,
  BarChart3,
  BarChart4,
  AreaChart,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Circle,
  CircleDot,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpLeft,
  Move,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  Diamond,
  Gem,
  Crown,
  Trophy,
  Medal,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeInfo,
  ClipboardPen,
  ClipboardCopy,
  ClipboardPaste,
  ClipboardX,
  FilePen,
  FileBarChart,
  FileStack,
  FileSymlink,
  FileWarning,
  FileHeart,
  FileLock,
  FileKey,
  Hash,
  Square,
  Triangle,
  Hexagon,
  Cross,
} from 'lucide-react';
import type { Tables } from '@/integrations/supabase/types';

// Comprehensive icon map for menu items
export const iconMap: Record<string, LucideIcon> = {
  Globe,
  Smartphone,
  Palette,
  Megaphone,
  Shield,
  Monitor,
  ShoppingCart,
  Code,
  Layout,
  Settings,
  Zap,
  Building,
  Briefcase,
  Users,
  FileText,
  Image,
  Video,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  CheckCircle,
  ArrowRight,
  ChevronRight,
  Star,
  Heart,
  Target,
  Rocket,
  TrendingUp,
  Database,
  Cpu,
  BarChart,
  Lightbulb,
  Award,
  Workflow,
  Search,
  PenTool,
  Home,
  Menu,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Navigation,
  Compass,
  MessageCircle,
  MessageSquare,
  Send,
  Bell,
  BellRing,
  Headphones,
  Mic,
  Folder,
  FolderOpen,
  File,
  FileCheck,
  Download,
  Upload,
  Save,
  Edit,
  Trash,
  Copy,
  Clipboard,
  DollarSign,
  CreditCard,
  Package,
  Store,
  TrendingDown,
  PieChart,
  LineChart,
  Share2,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  Share,
  Wifi,
  Bluetooth,
  Cloud,
  CloudUpload,
  CloudDownload,
  Server,
  HardDrive,
  Plus,
  Minus,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Filter,
  Grid,
  List,
  Layers,
  Link,
  ExternalLink,
  RefreshCw,
  Power,
  Camera,
  Music,
  Film,
  Gamepad2,
  Coffee,
  Gift,
  Flame,
  Droplet,
  Sun,
  Moon,
  Sparkles,
  Handshake,
  UserCheck,
  UserCog,
  ClipboardCheck,
  ClipboardList,
  CheckSquare,
  FileCheck2,
  FileQuestion,
  FileSearch,
  FileCode,
  FileImage,
  FileVideo,
  FileMusic,
  FileSpreadsheet,
  Presentation,
  BookOpen,
  GraduationCap,
  School,
  BookMarked,
  Newspaper,
  Radio,
  Podcast,
  Tv,
  MonitorSpeaker,
  Laptop,
  Tablet,
  MousePointerClick,
  Keyboard,
  Printer,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Code2,
  Brackets,
  Braces,
  Bug,
  TestTube,
  FlaskConical,
  Paintbrush,
  Paintbrush2,
  Brush,
  Eraser,
  Ruler,
  Scissors,
  Crop,
  Layers2,
  Layers3,
  Frame,
  Activity,
  Signal,
  Volume2,
  VolumeX,
  ShoppingBag,
  ShoppingBasket,
  Receipt,
  Tag,
  Tags,
  Percent,
  Ticket,
  QrCode,
  Barcode,
  ScanLine,
  LifeBuoy,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  PhoneOff,
  Plane,
  Car,
  Bike,
  Ship,
  Train,
  Bus,
  Navigation2,
  Map,
  MapPinned,
  Route,
  HeartPulse,
  Dumbbell,
  Stethoscope,
  Pill,
  Utensils,
  UtensilsCrossed,
  ChefHat,
  Wine,
  Beer,
  Building2,
  Factory,
  Warehouse,
  Hotel,
  Book,
  BookOpenCheck,
  School2,
  Wallet,
  Banknote,
  Coins,
  ReceiptText,
  Calculator,
  Scale,
  Gavel,
  FileJson,
  FileType,
  FileX,
  FilePlus,
  FileMinus,
  FileEdit,
  Users2,
  UserPlus,
  UserMinus,
  UserX,
  UserCircle,
  UserSquare,
  UserRound,
  Timer,
  TimerReset,
  TimerOff,
  CalendarDays,
  CalendarCheck,
  CalendarClock,
  CalendarX,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Sunrise,
  Sunset,
  Wind,
  Wrench,
  Hammer,
  Nut,
  Cog,
  Sliders,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  Key,
  KeyRound,
  Fingerprint,
  Scan,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Volume1,
  VideoOff,
  MicOff,
  AtSign,
  MailOpen,
  MailCheck,
  MailX,
  MessageSquareReply,
  MessageSquareText,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderCheck,
  FolderSearch,
  FolderKanban,
  FolderTree,
  BarChart2,
  BarChart3,
  BarChart4,
  AreaChart,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Circle,
  CircleDot,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpLeft,
  Move,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  Diamond,
  Gem,
  Crown,
  Trophy,
  Medal,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeInfo,
  ClipboardPen,
  ClipboardCopy,
  ClipboardPaste,
  ClipboardX,
  FilePen,
  FileBarChart,
  FileStack,
  FileSymlink,
  FileWarning,
  FileHeart,
  FileLock,
  FileKey,
  Hash,
  Square,
  Triangle,
  Hexagon,
  Cross,
};

// Helper to get icon component from name
export function getIconComponent(iconName: string | null | undefined): LucideIcon | null {
  if (!iconName) return null;
  return iconMap[iconName] || null;
}

// Alias for getIconComponent for compatibility
export function resolveIcon(iconName: string | null | undefined): LucideIcon | null {
  return getIconComponent(iconName);
}

// Get list of all available icon names
export function getAvailableIconNames(): string[] {
  return Object.keys(iconMap);
}

// Mega menu types
export interface MegaMenuLink {
  title: string;
  href: string;
  description?: string;
  iconName?: string;
  icon?: LucideIcon;
}

export interface MegaMenuSection {
  title: string;
  href?: string;
  description?: string;
  iconName?: string;
  icon?: LucideIcon;
  items?: MegaMenuLink[];
}

export interface MegaMenuDefinition {
  summaryTitle: string;
  summaryText: string;
  ctaLabel?: string;
  ctaHref?: string;
  sections: MegaMenuSection[];
}

// Type for menu items from database
export type MenuItem = Tables<"menu_items">;

// Extended menu item with children for tree structure
export type MenuTreeItem = MenuItem & {
  children?: MenuTreeItem[];
};

// Build hierarchical menu structure from flat list
export function buildMenuTree(items: MenuItem[]): MenuTreeItem[] {
  const itemMap: Record<string, MenuTreeItem> = {};
  const roots: MenuTreeItem[] = [];

  // First pass: create map of all items
  items.forEach(item => {
    itemMap[item.id] = { ...item, children: [] };
  });

  // Second pass: build tree structure
  items.forEach(item => {
    const mappedItem = itemMap[item.id];
    if (item.parent_id && itemMap[item.parent_id]) {
      const parent = itemMap[item.parent_id];
      if (!parent.children) parent.children = [];
      parent.children.push(mappedItem);
    } else {
      roots.push(mappedItem);
    }
  });

  // Sort by display_order
  const sortByOrder = (a: MenuItem, b: MenuItem) => 
    (a.display_order ?? 0) - (b.display_order ?? 0);

  roots.sort(sortByOrder);
  roots.forEach(root => {
    if (root.children) {
      root.children.sort(sortByOrder);
    }
  });

  return roots;
}

// Transform menu tree item to mega menu definition
export function transformToMegaMenu(
  item: MenuTreeItem, 
  pagesMap: Map<string, string>
): MegaMenuDefinition | null {
  if (!item) return null;

  const getUrl = (menuItem: MenuItem): string => {
    if (menuItem.url) return menuItem.url;
    if (menuItem.page_id && pagesMap.has(menuItem.page_id)) {
      return `/${pagesMap.get(menuItem.page_id)}`;
    }
    return '#';
  };

  // Build sections from children (categories)
  const sections: MegaMenuSection[] = (item.children || []).map(category => {
    const categoryIcon = resolveIcon(category.icon_name);
    
    // Build items from category children (sub-items)
    const items: MegaMenuLink[] = (category.children || []).map(subItem => ({
      title: subItem.label,
      href: getUrl(subItem),
      description: subItem.description || undefined,
      iconName: subItem.icon_name || undefined,
      icon: resolveIcon(subItem.icon_name) || undefined,
    }));

    return {
      title: category.label,
      href: getUrl(category),
      description: category.description || undefined,
      iconName: category.icon_name || undefined,
      icon: categoryIcon || undefined,
      items: items.length > 0 ? items : undefined,
    };
  });

  return {
    summaryTitle: item.mega_summary_title || item.label,
    summaryText: item.mega_summary_text || '',
    ctaLabel: item.mega_cta_label || undefined,
    ctaHref: item.mega_cta_href || undefined,
    sections,
  };
}

// Filter menu items by location
export function filterByLocation(items: MenuItem[], location: string): MenuItem[] {
  return items.filter(item => item.menu_location === location);
}

// Get URL for menu item (uses page slug or custom URL)
export function getMenuItemUrl(item: MenuItem): string {
  if (item.url) return item.url;
  return '#';
}
